"""rename address

Revision ID: 203e4a6fdc5b
Revises: 658cb1d5a919
Create Date: 2024-05-29 10:13:05.497092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203e4a6fdc5b'
down_revision = '658cb1d5a919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
