"""rename department

Revision ID: 658cb1d5a919
Revises: b94a52c5b760
Create Date: 2024-05-29 09:56:39.381024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658cb1d5a919'
down_revision = 'b94a52c5b760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
